In [1]:

TRAIN = "/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data"
TEST =  "/kaggle/input/datasets/samasiayushman/small-model-track/Testing/Testing/small_model_track_test-007/small_model_track_test"

In [2]:
import pandas as pd
import os
class_mapping = pd.read_csv(
    os.path.join(TRAIN, "/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/class_mapping.csv")
)

test = pd.read_csv(
    os.path.join(TEST, "/kaggle/input/datasets/samasiayushman/small-model-track/Testing/Testing/test.csv")
)

sample_submission = pd.read_csv(
    os.path.join(TEST, "/kaggle/input/datasets/samasiayushman/small-model-track/Testing/Testing/sample_submission.csv")
)

print("===== CLASS MAPPING =====")
print(class_mapping)
print(class_mapping.shape)

print("\n===== TEST =====")
print(test.head())
print(test.shape)
print(test.columns)

print("\n===== SAMPLE SUBMISSION =====")
print(sample_submission.head())
print(sample_submission.shape)
print(sample_submission.columns)

===== CLASS MAPPING =====
    action_id                         action_name
0           0                         0_Wash_face
1           1                       1_Brush_teeth
2           2                         2_Comb_hair
3           3                  3_Take_off_clothes
4           4                        4_Wipe_hands
5           5                    5_Put_on_clothes
6           6                       6_Drink_water
7           7                          7_Eat_food
8           8            8_Take_and_use_tableware
9           9                       9_Pour_drinks
10         10                      10_Stir_drinks
11         11                      11_Peel_fruits
12         12                  12_Sweep_the_floor
13         13                    13_Mop_the_floor
14         14                       14_Wipe_bowls
15         15          15_Wipe_windows_and_tables
16         16                     16_Fold_clothes
17         17                 17_Tap_the_keyboard
18         18                            18_Write
19         19                19_Make_a_phone_call
20         20                   20_Check_the_time
21         21                   21_Read_documents
22         22                       22_Turn_pages
23         23  23_Listen_to_music_with_headphones
24         24               24_Use_a_mobile_phone
25         25                         25_Watch_TV
26         26                       26_Play_games
27         27                    27_Take_a_selfie
28         28                     28_Jog_in_place
29         29                        29_Do_squats
30         30                 30_Do_jumping_jacks
31         31          31_Do_stretching_exercises
32         32                         32_Stand_up
33         33                         33_Lie_down
34         34                         34_Sit_down
35         35                        35_Do_lunges
36         36                             36_Walk
37         37                    37_Take_medicine
38         38                  38_Massage_oneself
39         39            39_Take_body_temperature
(40, 2)

===== TEST =====
                                   path  prediction
0  small_model_track_test/SM_test_0001/         NaN
1  small_model_track_test/SM_test_0002/         NaN
2  small_model_track_test/SM_test_0003/         NaN
3  small_model_track_test/SM_test_0004/         NaN
4  small_model_track_test/SM_test_0005/         NaN
(405, 2)
Index(['path', 'prediction'], dtype='object')

===== SAMPLE SUBMISSION =====
                                   path  prediction
0  small_model_track_test/SM_test_0001/          34
1  small_model_track_test/SM_test_0002/          34
2  small_model_track_test/SM_test_0003/          22
3  small_model_track_test/SM_test_0004/          21
4  small_model_track_test/SM_test_0005/           6
(405, 2)
Index(['path', 'prediction'], dtype='object')

In [3]:
import os

test_root = TEST
sample = os.path.join(test_root, "SM_test_0001")

print("===== TEST SAMPLE =====")
print(sample)

for root, dirs, files in os.walk(sample):
    level = root.replace(sample, "").count(os.sep)

    if level <= 3:
        indent = "  " * level
        print(f"{indent}{os.path.basename(root)}/")

        for f in files[:10]:
            print(f"{indent}  {f}")

        if len(files) > 10:
            print(f"{indent}  ... ({len(files)} files)")

===== TEST SAMPLE =====
/kaggle/input/datasets/samasiayushman/small-model-track/Testing/Testing/small_model_track_test-007/small_model_track_test/SM_test_0001
SM_test_0001/
  Skeleton/
    predictions/
      Color_2025-06-17_14-34-49.316_00000374.json
      Color_2025-06-17_14-34-48.616_00000367.json
      Color_2025-06-17_14-34-49.216_00000373.json
      Color_2025-06-17_14-34-47.716_00000358.json
      Color_2025-06-17_14-34-48.316_00000364.json
      Color_2025-06-17_14-34-48.216_00000363.json
      Color_2025-06-17_14-34-47.416_00000355.json
      Color_2025-06-17_14-34-48.516_00000366.json
      Color_2025-06-17_14-34-49.116_00000372.json
      Color_2025-06-17_14-34-48.116_00000362.json
      ... (20 files)
  Radar/
    radar_output_T2025-06-17_14-32-57.263.csv
  Thermal/
    frame_000903.jpg
    frame_000868.jpg
    frame_000869.jpg
    frame_000892.jpg
    frame_000864.jpg
    frame_000897.jpg
    frame_000899.jpg
    frame_000880.jpg
    frame_000896.jpg
    frame_000888.jpg
    ... (49 files)
  IR/
    IR_2025-06-17_14-34-48.816_00000369.png
    IR_2025-06-17_14-34-48.016_00000361.png
    IR_2025-06-17_14-34-48.316_00000364.png
    IR_2025-06-17_14-34-47.716_00000358.png
    IR_2025-06-17_14-34-48.116_00000362.png
    IR_2025-06-17_14-34-49.016_00000371.png
    IR_2025-06-17_14-34-48.916_00000370.png
    IR_2025-06-17_14-34-48.516_00000366.png
    IR_2025-06-17_14-34-48.416_00000365.png
    IR_2025-06-17_14-34-48.616_00000367.png
    ... (20 files)
  IMU/
    up(LA+RA+C).csv
    down(LL+RL).csv
  Depth_Color/
    Depth_2025-06-17_14-34-49.116_00000372_Color.png
    Depth_2025-06-17_14-34-48.816_00000369_Color.png
    Depth_2025-06-17_14-34-47.916_00000360_Color.png
    Depth_2025-06-17_14-34-48.716_00000368_Color.png
    Depth_2025-06-17_14-34-49.216_00000373_Color.png
    Depth_2025-06-17_14-34-47.516_00000356_Color.png
    Depth_2025-06-17_14-34-48.216_00000363_Color.png
    Depth_2025-06-17_14-34-48.116_00000362_Color.png
    Depth_2025-06-17_14-34-49.016_00000371_Color.png
    Depth_2025-06-17_14-34-48.616_00000367_Color.png
    ... (20 files)

In [4]:
print("\n===== TEST SAMPLE COUNTS =====")

for item in os.listdir(sample):
    path = os.path.join(sample, item)

    if os.path.isdir(path):
        count = sum(
            len(files)
            for _, _, files in os.walk(path)
        )
        print(f"{item:20s} {count}")
    else:
        print(f"{item:20s} FILE")

===== TEST SAMPLE COUNTS =====
Skeleton             20
Radar                1
Thermal              49
IR                   20
IMU                  2
Depth_Color          20

In [5]:
import os
import glob

TRAIN_DATA = TRAIN

radar_files = glob.glob(
    os.path.join(TRAIN_DATA, "Radar", "**", "*.csv"),
    recursive=True
)

print("===== RADAR DATASET AUDIT =====")
print("Radar CSV files:", len(radar_files))

empty = 0
nonempty = 0
total_data_rows = 0

for f in radar_files:
    with open(f, encoding="utf-8", errors="ignore") as fp:
        lines = fp.readlines()

    # header-only = no actual radar observations
    data_rows = max(0, len(lines) - 1)

    if data_rows == 0:
        empty += 1
    else:
        nonempty += 1
        total_data_rows += data_rows

print("Header-only files:", empty)
print("Files with measurements:", nonempty)
print("Total radar data rows:", total_data_rows)

===== RADAR DATASET AUDIT =====
Radar CSV files: 2914
Header-only files: 1505
Files with measurements: 1409
Total radar data rows: 545329

In [6]:
imu_files = glob.glob(
    os.path.join(TRAIN, "IMU", "**", "*.csv"),
    recursive=True
)

print("\n===== IMU DATASET AUDIT =====")
print("IMU CSV files:", len(imu_files))

for f in imu_files[:10]:
    print(f)

===== IMU DATASET AUDIT =====
IMU CSV files: 5806
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user17/4-1-3/up(LA+RA+C).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user17/4-1-3/down(LL+RL).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user17/4-1-1/up(LA+RA+C).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user17/4-1-1/down(LL+RL).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user17/4-1-2/up(LA+RA+C).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user17/4-1-2/down(LL+RL).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user1/3-2-1/up(LA+RA+C).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user1/3-2-1/down(LL+RL).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user1/1-1-3/up(LA+RA+C).csv
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/29_Do_squats/user1/1-1-3/down(LL+RL).csv

In [7]:
from collections import Counter

imu_names = Counter(
    os.path.basename(f)
    for f in imu_files
)

print("\nIMU file-name distribution:")
for name, count in imu_names.items():
    print(f"{name}: {count}")

IMU file-name distribution:
up(LA+RA+C).csv: 2870
down(LL+RL).csv: 2875
下(RL+LL).csv: 20
上(RA+LA+C).csv: 26
上(LA+RA+C)_.csv: 3
上(RLA+RA+C).csv: 4
下(LL+RL)).csv: 2
下 (LL+RL).csv: 6

In [8]:
import json

skeleton_files = glob.glob(
    os.path.join(TRAIN_DATA, "Skeleton", "**", "*.json"),
    recursive=True
)

print("\n===== SKELETON DATASET AUDIT =====")
print("Skeleton JSON files:", len(skeleton_files))

object_counts = Counter()
keypoint_counts = Counter()
score_counts = Counter()
invalid = 0

for f in skeleton_files:
    try:
        with open(f, encoding="utf-8") as fp:
            data = json.load(fp)

        object_counts[len(data)] += 1

        if data:
            keypoint_counts[len(data[0].get("keypoints", []))] += 1
            score_counts[len(data[0].get("keypoint_scores", []))] += 1

    except Exception:
        invalid += 1

print("Objects per JSON:", object_counts)
print("Keypoints:", keypoint_counts)
print("Scores:", score_counts)
print("Invalid JSON:", invalid)

===== SKELETON DATASET AUDIT =====
Skeleton JSON files: 86050
Objects per JSON: Counter({1: 82525, 2: 2667, 3: 833, 4: 25})
Keypoints: Counter({17: 86050})
Scores: Counter({17: 86050})
Invalid JSON: 0

In [9]:
import pandas as pd
import numpy as np
import os

trial = os.path.join(
    TRAIN_DATA,
    "IMU",
    "0_Wash_face",
    "user16",
    "1-1-1",
    
)

files = []

for f in os.listdir(trial):
    if f.endswith(".csv"):
        files.append(os.path.join(trial, f))

print("===== IMU NUMERIC FEATURES =====")

for f in files:

    print("\n" + "=" * 70)
    print(os.path.basename(f))

    df = pd.read_csv(f)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    # Convert everything possible to numeric
    numeric = df.apply(pd.to_numeric, errors="coerce")

    stats = pd.DataFrame({
        "min": numeric.min(),
        "max": numeric.max(),
        "mean": numeric.mean(),
        "std": numeric.std()
    })

    print(stats.to_string())

===== IMU NUMERIC FEATURES =====

======================================================================
up(LA+RA+C).csv
Rows: 137
Columns: 21
                 min        max       mean         std
时间               NaN        NaN        NaN         NaN
设备名称             NaN        NaN        NaN         NaN
加速度X(g)     -1.31000    0.91900   0.028044    0.587030
加速度Y(g)     -0.89000    1.01500  -0.055007    0.743527
加速度Z(g)     -0.68700    0.49400  -0.217555    0.213297
角速度X(°/s)  -74.28000   73.18100   4.608876   17.193833
角速度Y(°/s) -116.15000  134.27700   1.226073   22.303207
角速度Z(°/s) -111.81600   88.31800  -1.203737   22.067517
角度X(°)    -175.14000  176.65000 -13.842409  111.490927
角度Y(°)     -66.82000   84.21000  -1.013066   40.118143
角度Z(°)    -179.04000  166.42000 -14.949635   95.303178
磁场X(uT)    -38.62500   49.50000  -8.494526   35.899785
磁场Y(uT)    -60.25000    3.75000 -17.118613   18.045428
磁场Z(uT)    -55.71700   82.30000  10.165642   50.345343
四元数0()      -0.41281    0.56406  -0.028632    0.368430
四元数1()      -0.75317    0.76807  -0.127220    0.585443
四元数2()      -0.58640    0.79086   0.172575    0.483862
四元数3()      -0.78738    0.56769  -0.124987    0.481420
温度(°C)      27.40000   30.30000  28.537956    1.273897
版本号()            NaN        NaN        NaN         NaN
电量(%)       30.00000   60.00000  46.569343   12.511051

======================================================================
down(LL+RL).csv
Rows: 90
Columns: 21
                 min       max        mean        std
时间               NaN       NaN         NaN        NaN
设备名称             NaN       NaN         NaN        NaN
加速度X(g)      0.09700   0.20100    0.141600   0.027814
加速度Y(g)      0.96200   1.00000    0.981556   0.005490
加速度Z(g)     -0.04300   0.05100   -0.005633   0.018457
角速度X(°/s)  -11.10800  11.65800    0.163478   3.418401
角速度Y(°/s)  -14.64800  24.29200   -0.122756   3.757953
角速度Z(°/s)   -3.47900   5.85900    0.096300   1.490198
角度X(°)      88.13000  91.86000   90.323000   0.877197
角度Y(°)     -10.16000  -5.33000   -8.017556   1.352376
角度Z(°)    -177.18000 -69.77000 -123.415222  52.423185
磁场X(uT)    -45.62500  -2.37500  -24.575000  19.859220
磁场Y(uT)    -31.00000   7.75000  -11.905556  18.232487
磁场Z(uT)    -14.78300  83.50800   34.289456  45.117612
四元数0()       0.04645   0.61624    0.337151   0.271144
四元数1()      -0.02448   0.55496    0.264079   0.280552
四元数2()      -0.72128  -0.45334   -0.583504   0.123516
四元数3()      -0.70926  -0.33844   -0.531490   0.167943
温度(°C)      25.80000  27.00000   26.386667   0.603212
版本号()            NaN       NaN         NaN        NaN
电量(%)       30.00000  50.00000   40.222222  10.053540

In [10]:
import os
import glob
import pandas as pd
import numpy as np

actions = [
    "0_Wash_face",
    "29_Do_squats",
    "30_Do_jumping_jacks",
    "36_Walk",
    "17_Tap_the_keyboard",
    "18_Write"
]

print("===== IMU ACTION COMPARISON =====")

for action in actions:

    files = glob.glob(
        os.path.join(
            TRAIN_DATA,
            "IMU",
            action,
            "*",
            "*",
            "*.csv"
        )
    )

    print("\n" + "=" * 70)
    print(action)
    print("CSV files:", len(files))

    # Take first valid file
    f = files[0]

    df = pd.read_csv(f)
    numeric = df.apply(pd.to_numeric, errors="coerce")

    for col in [
        "加速度X(g)",
        "加速度Y(g)",
        "加速度Z(g)",
        "角速度X(°/s)",
        "角速度Y(°/s)",
        "角速度Z(°/s)"
    ]:
        print(
            f"{col:15s} "
            f"mean={numeric[col].mean():8.3f} "
            f"std={numeric[col].std():8.3f}"
        )

===== IMU ACTION COMPARISON =====

======================================================================
0_Wash_face
CSV files: 88
加速度X(g)         mean=  -0.202 std=   0.469
加速度Y(g)         mean=   0.635 std=   0.633
加速度Z(g)         mean=   0.297 std=   0.490
角速度X(°/s)       mean= -39.429 std= 122.008
角速度Y(°/s)       mean=   2.167 std=  49.693
角速度Z(°/s)       mean=  41.618 std= 132.900

======================================================================
29_Do_squats
CSV files: 154
加速度X(g)         mean=  -0.424 std=   0.689
加速度Y(g)         mean=   0.731 std=   0.617
加速度Z(g)         mean=   0.127 std=   0.638
角速度X(°/s)       mean=  11.138 std= 117.660
角速度Y(°/s)       mean=  10.883 std=  75.940
角速度Z(°/s)       mean=  20.464 std=  98.878

======================================================================
30_Do_jumping_jacks
CSV files: 88
加速度X(g)         mean=   0.253 std=   1.908
加速度Y(g)         mean=   2.379 std=   1.545
加速度Z(g)         mean=  -0.497 std=   0.943
角速度X(°/s)       mean=  52.552 std= 319.220
角速度Y(°/s)       mean=  30.933 std= 254.170
角速度Z(°/s)       mean=   6.244 std= 377.726

======================================================================
36_Walk
CSV files: 660
加速度X(g)         mean=   0.181 std=   0.494
加速度Y(g)         mean=   0.360 std=   0.913
加速度Z(g)         mean=  -0.190 std=   0.202
角速度X(°/s)       mean=   8.293 std=  44.251
角速度Y(°/s)       mean=  25.145 std= 135.025
角速度Z(°/s)       mean=   3.201 std=  50.989

======================================================================
17_Tap_the_keyboard
CSV files: 172
加速度X(g)         mean=  -0.564 std=   0.298
加速度Y(g)         mean=   0.473 std=   0.287
加速度Z(g)         mean=   0.283 std=   0.498
角速度X(°/s)       mean=  -5.474 std=  28.638
角速度Y(°/s)       mean=  -4.716 std=  25.403
角速度Z(°/s)       mean=  -3.249 std=  37.524

======================================================================
18_Write
CSV files: 76
加速度X(g)         mean=   0.004 std=   0.164
加速度Y(g)         mean=   0.585 std=   0.282
加速度Z(g)         mean=   0.680 std=   0.341
角速度X(°/s)       mean=   0.785 std=   8.010
角速度Y(°/s)       mean=  -0.253 std=  18.991
角速度Z(°/s)       mean=   0.452 std=  11.096

In [11]:
import os
from collections import defaultdict

ROOT = "/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data"

modalities = [
    "Depth_Color",
    "IR",
    "Thermal",
    "IMU",
    "Radar",
    "Skeleton"
]

for modality in modalities:
    base = os.path.join(ROOT, modality)

    print("\n" + "="*70)
    print(modality)

    if not os.path.exists(base):
        print("NOT FOUND")
        continue

    actions = sorted(
        d for d in os.listdir(base)
        if os.path.isdir(os.path.join(base, d))
    )

    print("Actions:", len(actions))

    for action in actions:
        action_path = os.path.join(base, action)

        users = sorted(
            d for d in os.listdir(action_path)
            if os.path.isdir(os.path.join(action_path, d))
        )

        print(f"{action:40s} users={len(users)}")

======================================================================
Depth_Color
Actions: 40
0_Wash_face                              users=11
10_Stir_drinks                           users=16
11_Peel_fruits                           users=16
12_Sweep_the_floor                       users=16
13_Mop_the_floor                         users=14
14_Wipe_bowls                            users=11
15_Wipe_windows_and_tables               users=12
16_Fold_clothes                          users=8
17_Tap_the_keyboard                      users=16
18_Write                                 users=11
19_Make_a_phone_call                     users=12
1_Brush_teeth                            users=13
20_Check_the_time                        users=15
21_Read_documents                        users=16
22_Turn_pages                            users=13
23_Listen_to_music_with_headphones       users=16
24_Use_a_mobile_phone                    users=11
25_Watch_TV                              users=3
26_Play_games                            users=6
27_Take_a_selfie                         users=13
28_Jog_in_place                          users=12
29_Do_squats                             users=15
2_Comb_hair                              users=16
30_Do_jumping_jacks                      users=14
31_Do_stretching_exercises               users=14
32_Stand_up                              users=17
33_Lie_down                              users=8
34_Sit_down                              users=16
35_Do_lunges                             users=8
36_Walk                                  users=17
37_Take_medicine                         users=16
38_Massage_oneself                       users=12
39_Take_body_temperature                 users=13
3_Take_off_clothes                       users=9
4_Wipe_hands                             users=16
5_Put_on_clothes                         users=12
6_Drink_water                            users=17
7_Eat_food                               users=18
8_Take_and_use_tableware                 users=12
9_Pour_drinks                            users=17

======================================================================
IR
Actions: 40
0_Wash_face                              users=11
10_Stir_drinks                           users=16
11_Peel_fruits                           users=16
12_Sweep_the_floor                       users=16
13_Mop_the_floor                         users=14
14_Wipe_bowls                            users=11
15_Wipe_windows_and_tables               users=12
16_Fold_clothes                          users=8
17_Tap_the_keyboard                      users=16
18_Write                                 users=11
19_Make_a_phone_call                     users=12
1_Brush_teeth                            users=13
20_Check_the_time                        users=15
21_Read_documents                        users=16
22_Turn_pages                            users=13
23_Listen_to_music_with_headphones       users=16
24_Use_a_mobile_phone                    users=11
25_Watch_TV                              users=3
26_Play_games                            users=6
27_Take_a_selfie                         users=13
28_Jog_in_place                          users=12
29_Do_squats                             users=15
2_Comb_hair                              users=16
30_Do_jumping_jacks                      users=14
31_Do_stretching_exercises               users=14
32_Stand_up                              users=17
33_Lie_down                              users=8
34_Sit_down                              users=16
35_Do_lunges                             users=8
36_Walk                                  users=17
37_Take_medicine                         users=16
38_Massage_oneself                       users=12
39_Take_body_temperature                 users=13
3_Take_off_clothes                       users=9
4_Wipe_hands                             users=16
5_Put_on_clothes                         users=12
6_Drink_water                            users=17
7_Eat_food                               users=18
8_Take_and_use_tableware                 users=12
9_Pour_drinks                            users=17

======================================================================
Thermal
Actions: 40
0_Wash_face                              users=11
10_Stir_drinks                           users=16
11_Peel_fruits                           users=16
12_Sweep_the_floor                       users=14
13_Mop_the_floor                         users=13
14_Wipe_bowls                            users=11
15_Wipe_windows_and_tables               users=12
16_Fold_clothes                          users=8
17_Tap_the_keyboard                      users=16
18_Write                                 users=11
19_Make_a_phone_call                     users=12
1_Brush_teeth                            users=13
20_Check_the_time                        users=15
21_Read_documents                        users=17
22_Turn_pages                            users=13
23_Listen_to_music_with_headphones       users=17
24_Use_a_mobile_phone                    users=10
25_Watch_TV                              users=3
26_Play_games                            users=6
27_Take_a_selfie                         users=13
28_Jog_in_place                          users=12
29_Do_squats                             users=15
2_Comb_hair                              users=16
30_Do_jumping_jacks                      users=14
31_Do_stretching_exercises               users=14
32_Stand_up                              users=17
33_Lie_down                              users=9
34_Sit_down                              users=15
35_Do_lunges                             users=8
36_Walk                                  users=17
37_Take_medicine                         users=16
38_Massage_oneself                       users=13
39_Take_body_temperature                 users=12
3_Take_off_clothes                       users=9
4_Wipe_hands                             users=16
5_Put_on_clothes                         users=12
6_Drink_water                            users=17
7_Eat_food                               users=18
8_Take_and_use_tableware                 users=12
9_Pour_drinks                            users=17

======================================================================
IMU
Actions: 40
0_Wash_face                              users=11
10_Stir_drinks                           users=16
11_Peel_fruits                           users=16
12_Sweep_the_floor                       users=16
13_Mop_the_floor                         users=14
14_Wipe_bowls                            users=11
15_Wipe_windows_and_tables               users=12
16_Fold_clothes                          users=8
17_Tap_the_keyboard                      users=16
18_Write                                 users=11
19_Make_a_phone_call                     users=12
1_Brush_teeth                            users=13
20_Check_the_time                        users=15
21_Read_documents                        users=16
22_Turn_pages                            users=13
23_Listen_to_music_with_headphones       users=16
24_Use_a_mobile_phone                    users=11
25_Watch_TV                              users=3
26_Play_games                            users=6
27_Take_a_selfie                         users=13
28_Jog_in_place                          users=12
29_Do_squats                             users=15
2_Comb_hair                              users=16
30_Do_jumping_jacks                      users=14
31_Do_stretching_exercises               users=14
32_Stand_up                              users=17
33_Lie_down                              users=8
34_Sit_down                              users=16
35_Do_lunges                             users=8
36_Walk                                  users=17
37_Take_medicine                         users=16
38_Massage_oneself                       users=12
39_Take_body_temperature                 users=13
3_Take_off_clothes                       users=9
4_Wipe_hands                             users=16
5_Put_on_clothes                         users=12
6_Drink_water                            users=17
7_Eat_food                               users=18
8_Take_and_use_tableware                 users=12
9_Pour_drinks                            users=17

======================================================================
Radar
Actions: 40
0_Wash_face                              users=11
10_Stir_drinks                           users=16
11_Peel_fruits                           users=16
12_Sweep_the_floor                       users=16
13_Mop_the_floor                         users=14
14_Wipe_bowls                            users=11
15_Wipe_windows_and_tables               users=12
16_Fold_clothes                          users=7
17_Tap_the_keyboard                      users=16
18_Write                                 users=11
19_Make_a_phone_call                     users=12
1_Brush_teeth                            users=13
20_Check_the_time                        users=15
21_Read_documents                        users=16
22_Turn_pages                            users=13
23_Listen_to_music_with_headphones       users=16
24_Use_a_mobile_phone                    users=11
25_Watch_TV                              users=3
26_Play_games                            users=6
27_Take_a_selfie                         users=13
28_Jog_in_place                          users=12
29_Do_squats                             users=15
2_Comb_hair                              users=16
30_Do_jumping_jacks                      users=14
31_Do_stretching_exercises               users=14
32_Stand_up                              users=17
33_Lie_down                              users=8
34_Sit_down                              users=16
35_Do_lunges                             users=8
36_Walk                                  users=17
37_Take_medicine                         users=16
38_Massage_oneself                       users=12
39_Take_body_temperature                 users=13
3_Take_off_clothes                       users=9
4_Wipe_hands                             users=16
5_Put_on_clothes                         users=11
6_Drink_water                            users=17
7_Eat_food                               users=18
8_Take_and_use_tableware                 users=12
9_Pour_drinks                            users=17

======================================================================
Skeleton
Actions: 40
0_Wash_face                              users=11
10_Stir_drinks                           users=16
11_Peel_fruits                           users=16
12_Sweep_the_floor                       users=16
13_Mop_the_floor                         users=14
14_Wipe_bowls                            users=11
15_Wipe_windows_and_tables               users=12
16_Fold_clothes                          users=8
17_Tap_the_keyboard                      users=16
18_Write                                 users=11
19_Make_a_phone_call                     users=12
1_Brush_teeth                            users=13
20_Check_the_time                        users=15
21_Read_documents                        users=16
22_Turn_pages                            users=13
23_Listen_to_music_with_headphones       users=16
24_Use_a_mobile_phone                    users=11
25_Watch_TV                              users=3
26_Play_games                            users=6
27_Take_a_selfie                         users=13
28_Jog_in_place                          users=12
29_Do_squats                             users=15
2_Comb_hair                              users=16
30_Do_jumping_jacks                      users=14
31_Do_stretching_exercises               users=14
32_Stand_up                              users=17
33_Lie_down                              users=8
34_Sit_down                              users=16
35_Do_lunges                             users=8
36_Walk                                  users=17
37_Take_medicine                         users=16
38_Massage_oneself                       users=12
39_Take_body_temperature                 users=13
3_Take_off_clothes                       users=9
4_Wipe_hands                             users=16
5_Put_on_clothes                         users=12
6_Drink_water                            users=17
7_Eat_food                               users=18
8_Take_and_use_tableware                 users=12
9_Pour_drinks                            users=17

In [12]:
import os
from collections import defaultdict

ROOT = "/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data"

modalities = [
    "Depth_Color",
    "IR",
    "Thermal",
    "IMU",
    "Radar",
    "Skeleton"
]

for modality in modalities:

    base = os.path.join(ROOT, modality)

    print("\n" + "=" * 80)
    print(modality)

    for action in sorted(os.listdir(base)):

        action_path = os.path.join(base, action)

        if not os.path.isdir(action_path):
            continue

        user_trials = {}

        for user in sorted(os.listdir(action_path)):

            user_path = os.path.join(action_path, user)

            if not os.path.isdir(user_path):
                continue

            trials = [
                x for x in os.listdir(user_path)
                if os.path.isdir(os.path.join(user_path, x))
            ]

            user_trials[user] = len(trials)

        total_trials = sum(user_trials.values())

        print(
            f"{action:40s} "
            f"users={len(user_trials):2d} "
            f"trials={total_trials:3d}"
        )

================================================================================
Depth_Color
0_Wash_face                              users=11 trials= 44
10_Stir_drinks                           users=16 trials=117
11_Peel_fruits                           users=16 trials=106
12_Sweep_the_floor                       users=16 trials= 63
13_Mop_the_floor                         users=14 trials= 56
14_Wipe_bowls                            users=11 trials= 35
15_Wipe_windows_and_tables               users=12 trials= 52
16_Fold_clothes                          users= 8 trials= 24
17_Tap_the_keyboard                      users=16 trials= 86
18_Write                                 users=11 trials= 38
19_Make_a_phone_call                     users=12 trials= 43
1_Brush_teeth                            users=13 trials= 48
20_Check_the_time                        users=15 trials= 94
21_Read_documents                        users=16 trials= 73
22_Turn_pages                            users=13 trials= 59
23_Listen_to_music_with_headphones       users=16 trials= 75
24_Use_a_mobile_phone                    users=11 trials= 48
25_Watch_TV                              users= 3 trials= 12
26_Play_games                            users= 6 trials= 40
27_Take_a_selfie                         users=13 trials= 41
28_Jog_in_place                          users=12 trials= 37
29_Do_squats                             users=15 trials= 77
2_Comb_hair                              users=16 trials= 54
30_Do_jumping_jacks                      users=14 trials= 44
31_Do_stretching_exercises               users=14 trials= 85
32_Stand_up                              users=17 trials= 84
33_Lie_down                              users= 8 trials= 33
34_Sit_down                              users=16 trials=147
35_Do_lunges                             users= 8 trials= 26
36_Walk                                  users=17 trials=335
37_Take_medicine                         users=16 trials= 68
38_Massage_oneself                       users=12 trials= 62
39_Take_body_temperature                 users=13 trials= 55
3_Take_off_clothes                       users= 9 trials= 41
4_Wipe_hands                             users=16 trials= 70
5_Put_on_clothes                         users=12 trials= 57
6_Drink_water                            users=17 trials=120
7_Eat_food                               users=18 trials=154
8_Take_and_use_tableware                 users=12 trials= 97
9_Pour_drinks                            users=17 trials=131

================================================================================
IR
0_Wash_face                              users=11 trials= 44
10_Stir_drinks                           users=16 trials=117
11_Peel_fruits                           users=16 trials=106
12_Sweep_the_floor                       users=16 trials= 63
13_Mop_the_floor                         users=14 trials= 56
14_Wipe_bowls                            users=11 trials= 35
15_Wipe_windows_and_tables               users=12 trials= 52
16_Fold_clothes                          users= 8 trials= 24
17_Tap_the_keyboard                      users=16 trials= 86
18_Write                                 users=11 trials= 38
19_Make_a_phone_call                     users=12 trials= 43
1_Brush_teeth                            users=13 trials= 48
20_Check_the_time                        users=15 trials= 94
21_Read_documents                        users=16 trials= 73
22_Turn_pages                            users=13 trials= 59
23_Listen_to_music_with_headphones       users=16 trials= 75
24_Use_a_mobile_phone                    users=11 trials= 48
25_Watch_TV                              users= 3 trials= 12
26_Play_games                            users= 6 trials= 40
27_Take_a_selfie                         users=13 trials= 41
28_Jog_in_place                          users=12 trials= 37
29_Do_squats                             users=15 trials= 77
2_Comb_hair                              users=16 trials= 54
30_Do_jumping_jacks                      users=14 trials= 44
31_Do_stretching_exercises               users=14 trials= 85
32_Stand_up                              users=17 trials= 84
33_Lie_down                              users= 8 trials= 33
34_Sit_down                              users=16 trials=147
35_Do_lunges                             users= 8 trials= 26
36_Walk                                  users=17 trials=335
37_Take_medicine                         users=16 trials= 69
38_Massage_oneself                       users=12 trials= 62
39_Take_body_temperature                 users=13 trials= 55
3_Take_off_clothes                       users= 9 trials= 41
4_Wipe_hands                             users=16 trials= 70
5_Put_on_clothes                         users=12 trials= 57
6_Drink_water                            users=17 trials=120
7_Eat_food                               users=18 trials=155
8_Take_and_use_tableware                 users=12 trials= 97
9_Pour_drinks                            users=17 trials=131

================================================================================
Thermal
0_Wash_face                              users=11 trials= 41
10_Stir_drinks                           users=16 trials=120
11_Peel_fruits                           users=16 trials=104
12_Sweep_the_floor                       users=14 trials= 57
13_Mop_the_floor                         users=13 trials= 53
14_Wipe_bowls                            users=11 trials= 33
15_Wipe_windows_and_tables               users=12 trials= 53
16_Fold_clothes                          users= 8 trials= 24
17_Tap_the_keyboard                      users=16 trials= 85
18_Write                                 users=11 trials= 39
19_Make_a_phone_call                     users=12 trials= 42
1_Brush_teeth                            users=13 trials= 47
20_Check_the_time                        users=15 trials= 93
21_Read_documents                        users=17 trials= 80
22_Turn_pages                            users=13 trials= 59
23_Listen_to_music_with_headphones       users=17 trials= 77
24_Use_a_mobile_phone                    users=10 trials= 45
25_Watch_TV                              users= 3 trials= 11
26_Play_games                            users= 6 trials= 40
27_Take_a_selfie                         users=13 trials= 41
28_Jog_in_place                          users=12 trials= 36
29_Do_squats                             users=15 trials= 73
2_Comb_hair                              users=16 trials= 54
30_Do_jumping_jacks                      users=14 trials= 44
31_Do_stretching_exercises               users=14 trials= 73
32_Stand_up                              users=17 trials= 85
33_Lie_down                              users= 9 trials= 39
34_Sit_down                              users=15 trials=133
35_Do_lunges                             users= 8 trials= 26
36_Walk                                  users=17 trials=324
37_Take_medicine                         users=16 trials= 69
38_Massage_oneself                       users=13 trials= 68
39_Take_body_temperature                 users=12 trials= 54
3_Take_off_clothes                       users= 9 trials= 41
4_Wipe_hands                             users=16 trials= 71
5_Put_on_clothes                         users=12 trials= 54
6_Drink_water                            users=17 trials=122
7_Eat_food                               users=18 trials=154
8_Take_and_use_tableware                 users=12 trials= 94
9_Pour_drinks                            users=17 trials=133

================================================================================
IMU
0_Wash_face                              users=11 trials= 44
10_Stir_drinks                           users=16 trials=115
11_Peel_fruits                           users=16 trials=105
12_Sweep_the_floor                       users=16 trials= 63
13_Mop_the_floor                         users=14 trials= 53
14_Wipe_bowls                            users=11 trials= 35
15_Wipe_windows_and_tables               users=12 trials= 49
16_Fold_clothes                          users= 8 trials= 24
17_Tap_the_keyboard                      users=16 trials= 86
18_Write                                 users=11 trials= 38
19_Make_a_phone_call                     users=12 trials= 43
1_Brush_teeth                            users=13 trials= 48
20_Check_the_time                        users=15 trials= 94
21_Read_documents                        users=16 trials= 73
22_Turn_pages                            users=13 trials= 59
23_Listen_to_music_with_headphones       users=16 trials= 74
24_Use_a_mobile_phone                    users=11 trials= 47
25_Watch_TV                              users= 3 trials= 12
26_Play_games                            users= 6 trials= 40
27_Take_a_selfie                         users=13 trials= 41
28_Jog_in_place                          users=12 trials= 37
29_Do_squats                             users=15 trials= 77
2_Comb_hair                              users=16 trials= 54
30_Do_jumping_jacks                      users=14 trials= 44
31_Do_stretching_exercises               users=14 trials= 85
32_Stand_up                              users=17 trials= 84
33_Lie_down                              users= 8 trials= 33
34_Sit_down                              users=16 trials=146
35_Do_lunges                             users= 8 trials= 26
36_Walk                                  users=17 trials=330
37_Take_medicine                         users=16 trials= 68
38_Massage_oneself                       users=12 trials= 62
39_Take_body_temperature                 users=13 trials= 55
3_Take_off_clothes                       users= 9 trials= 41
4_Wipe_hands                             users=16 trials= 70
5_Put_on_clothes                         users=12 trials= 57
6_Drink_water                            users=17 trials=116
7_Eat_food                               users=18 trials=153
8_Take_and_use_tableware                 users=12 trials= 96
9_Pour_drinks                            users=17 trials=126

================================================================================
Radar
0_Wash_face                              users=11 trials= 44
10_Stir_drinks                           users=16 trials=116
11_Peel_fruits                           users=16 trials=106
12_Sweep_the_floor                       users=16 trials= 63
13_Mop_the_floor                         users=14 trials= 56
14_Wipe_bowls                            users=11 trials= 35
15_Wipe_windows_and_tables               users=12 trials= 51
16_Fold_clothes                          users= 7 trials= 21
17_Tap_the_keyboard                      users=16 trials= 86
18_Write                                 users=11 trials= 38
19_Make_a_phone_call                     users=12 trials= 43
1_Brush_teeth                            users=13 trials= 48
20_Check_the_time                        users=15 trials= 94
21_Read_documents                        users=16 trials= 73
22_Turn_pages                            users=13 trials= 59
23_Listen_to_music_with_headphones       users=16 trials= 75
24_Use_a_mobile_phone                    users=11 trials= 48
25_Watch_TV                              users= 3 trials= 12
26_Play_games                            users= 6 trials= 40
27_Take_a_selfie                         users=13 trials= 41
28_Jog_in_place                          users=12 trials= 37
29_Do_squats                             users=15 trials= 77
2_Comb_hair                              users=16 trials= 54
30_Do_jumping_jacks                      users=14 trials= 44
31_Do_stretching_exercises               users=14 trials= 85
32_Stand_up                              users=17 trials= 84
33_Lie_down                              users= 8 trials= 33
34_Sit_down                              users=16 trials=147
35_Do_lunges                             users= 8 trials= 26
36_Walk                                  users=17 trials=333
37_Take_medicine                         users=16 trials= 68
38_Massage_oneself                       users=12 trials= 62
39_Take_body_temperature                 users=13 trials= 50
3_Take_off_clothes                       users= 9 trials= 41
4_Wipe_hands                             users=16 trials= 70
5_Put_on_clothes                         users=11 trials= 54
6_Drink_water                            users=17 trials=120
7_Eat_food                               users=18 trials=154
8_Take_and_use_tableware                 users=12 trials= 96
9_Pour_drinks                            users=17 trials=130

================================================================================
Skeleton
0_Wash_face                              users=11 trials= 44
10_Stir_drinks                           users=16 trials=117
11_Peel_fruits                           users=16 trials=106
12_Sweep_the_floor                       users=16 trials= 63
13_Mop_the_floor                         users=14 trials= 56
14_Wipe_bowls                            users=11 trials= 35
15_Wipe_windows_and_tables               users=12 trials= 52
16_Fold_clothes                          users= 8 trials= 24
17_Tap_the_keyboard                      users=16 trials= 86
18_Write                                 users=11 trials= 38
19_Make_a_phone_call                     users=12 trials= 43
1_Brush_teeth                            users=13 trials= 48
20_Check_the_time                        users=15 trials= 94
21_Read_documents                        users=16 trials= 73
22_Turn_pages                            users=13 trials= 59
23_Listen_to_music_with_headphones       users=16 trials= 75
24_Use_a_mobile_phone                    users=11 trials= 48
25_Watch_TV                              users= 3 trials= 12
26_Play_games                            users= 6 trials= 40
27_Take_a_selfie                         users=13 trials= 41
28_Jog_in_place                          users=12 trials= 37
29_Do_squats                             users=15 trials= 77
2_Comb_hair                              users=16 trials= 54
30_Do_jumping_jacks                      users=14 trials= 44
31_Do_stretching_exercises               users=14 trials= 85
32_Stand_up                              users=17 trials= 84
33_Lie_down                              users= 8 trials= 33
34_Sit_down                              users=16 trials=147
35_Do_lunges                             users= 8 trials= 26
36_Walk                                  users=17 trials=335
37_Take_medicine                         users=16 trials= 68
38_Massage_oneself                       users=12 trials= 62
39_Take_body_temperature                 users=13 trials= 55
3_Take_off_clothes                       users= 9 trials= 41
4_Wipe_hands                             users=16 trials= 70
5_Put_on_clothes                         users=12 trials= 57
6_Drink_water                            users=17 trials=120
7_Eat_food                               users=18 trials=154
8_Take_and_use_tableware                 users=12 trials= 97
9_Pour_drinks                            users=17 trials=131

---

# Build a TRAIN MANIFEST

In [13]:
import os
import glob
import pandas as pd

TRAIN_DATA = "/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data"

modalities = [
    "Depth_Color",
    "IR",
    "Thermal",
    "IMU",
    "Radar",
    "Skeleton"
]

rows = []

for action in sorted(os.listdir(os.path.join(TRAIN_DATA, "Skeleton"))):

    action_path = os.path.join(TRAIN_DATA, "Skeleton", action)

    if not os.path.isdir(action_path):
        continue

    label = int(action.split("_")[0])

    for user in sorted(os.listdir(action_path)):

        user_path = os.path.join(action_path, user)

        if not os.path.isdir(user_path):
            continue

        for trial in sorted(os.listdir(user_path)):

            trial_path = os.path.join(user_path, trial)

            if not os.path.isdir(trial_path):
                continue

            row = {
                "action": action,
                "label": label,
                "user": user,
                "trial": trial
            }

            # Skeleton
            row["skeleton"] = len(
                glob.glob(
                    os.path.join(
                        trial_path,
                        "predictions",
                        "*.json"
                    )
                )
            )

            # Other modalities
            for modality in modalities:

                if modality == "Skeleton":
                    continue

                p = os.path.join(
                    TRAIN_DATA,
                    modality,
                    action,
                    user,
                    trial
                )

                if modality == "IMU":
                    count = len(glob.glob(os.path.join(p, "*.csv")))

                elif modality == "Radar":
                    count = len(glob.glob(os.path.join(p, "*.csv")))

                else:
                    count = len(glob.glob(os.path.join(p, "*")))

                row[modality.lower()] = count

            rows.append(row)

manifest = pd.DataFrame(rows)

print("Number of training trials:", len(manifest))
print()
print(manifest.head())

Number of training trials: 2931

        action  label    user  trial  skeleton  depth_color  ir  thermal  imu  \
0  0_Wash_face      0  user16  1-1-1        47           47  47      106    2
1  0_Wash_face      0  user16  1-1-2        55           55  55      135    2
2  0_Wash_face      0  user16  1-1-3        22           22  22       55    2
3  0_Wash_face      0  user18  7-1-1        20           20  20       44    2
4  0_Wash_face      0  user18  7-1-2        13           13  13       19    2

   radar
0      1
1      1
2      1
3      1
4      1

In [14]:
print("\n===== CLASS DISTRIBUTION =====")
print(
    manifest.groupby(["label", "action"])
    .size()
    .to_string()
)

===== CLASS DISTRIBUTION =====
label  action
0      0_Wash_face                            44
1      1_Brush_teeth                          48
2      2_Comb_hair                            54
3      3_Take_off_clothes                     41
4      4_Wipe_hands                           70
5      5_Put_on_clothes                       57
6      6_Drink_water                         120
7      7_Eat_food                            154
8      8_Take_and_use_tableware               97
9      9_Pour_drinks                         131
10     10_Stir_drinks                        117
11     11_Peel_fruits                        106
12     12_Sweep_the_floor                     63
13     13_Mop_the_floor                       56
14     14_Wipe_bowls                          35
15     15_Wipe_windows_and_tables             52
16     16_Fold_clothes                        24
17     17_Tap_the_keyboard                    86
18     18_Write                               38
19     19_Make_a_phone_call                   43
20     20_Check_the_time                      94
21     21_Read_documents                      73
22     22_Turn_pages                          59
23     23_Listen_to_music_with_headphones     75
24     24_Use_a_mobile_phone                  48
25     25_Watch_TV                            12
26     26_Play_games                          40
27     27_Take_a_selfie                       41
28     28_Jog_in_place                        37
29     29_Do_squats                           77
30     30_Do_jumping_jacks                    44
31     31_Do_stretching_exercises             85
32     32_Stand_up                            84
33     33_Lie_down                            33
34     34_Sit_down                           147
35     35_Do_lunges                           26
36     36_Walk                               335
37     37_Take_medicine                       68
38     38_Massage_oneself                     62
39     39_Take_body_temperature               55

In [15]:
print("\n===== USER DISTRIBUTION =====")

print(
    manifest.groupby("user")["label"]
    .count()
)

===== USER DISTRIBUTION =====
user
user1     149
user16    186
user17    166
user18    178
user19    186
user2     167
user20    159
user21    133
user22    191
user23    131
user24    159
user3     161
user4     134
user5     100
user6     201
user7     184
user8     165
user9     181
Name: label, dtype: int64

In [16]:
print("\n===== MISSING MODALITIES =====")

for col in [
    "depth_color",
    "ir",
    "thermal",
    "imu",
    "radar",
    "skeleton"
]:
    print(
        f"{col:15s}: "
        f"{(manifest[col] == 0).sum()} missing"
    )

===== MISSING MODALITIES =====
depth_color    : 0 missing
ir             : 0 missing
thermal        : 145 missing
imu            : 28 missing
radar          : 17 missing
skeleton       : 0 missing

In [17]:
print("\n===== MODALITY COUNTS =====")

print(
    manifest[
        [
            "depth_color",
            "ir",
            "thermal",
            "imu",
            "radar",
            "skeleton"
        ]
    ].describe()
)

===== MODALITY COUNTS =====
       depth_color           ir      thermal          imu       radar  \
count  2931.000000  2931.000000  2931.000000  2931.000000  2931.00000
mean     29.300239    29.300239    66.312521     1.980894     0.99420
std      21.899801    21.899801    58.194149     0.194577     0.07595
min       1.000000     1.000000     0.000000     0.000000     0.00000
25%      14.000000    14.000000    29.000000     2.000000     1.00000
50%      24.000000    24.000000    53.000000     2.000000     1.00000
75%      38.000000    38.000000    88.000000     2.000000     1.00000
max     236.000000   236.000000   595.000000     2.000000     1.00000

          skeleton
count  2931.000000
mean     29.358581
std      22.023429
min       1.000000
25%      14.000000
50%      24.000000
75%      38.000000
max     236.000000

---

In [18]:
import os
import glob
import re
import pandas as pd

TRAIN = "/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data"
TEST = "/kaggle/input/datasets/samasiayushman/small-model-track/Testing/Testing/small_model_track_test-007/small_model_track_test"

# Training users
users = []

for action in os.listdir(TRAIN + "/Skeleton"):
    action_dir = os.path.join(TRAIN, "Skeleton", action)

    if not os.path.isdir(action_dir):
        continue

    for user in os.listdir(action_dir):
        if user.startswith("user"):
            users.append(user)

print("Training users:")
print(sorted(set(users), key=lambda x: int(x.replace("user", ""))))

print()
print("Number of users:", len(set(users)))

Training users:
['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user16', 'user17', 'user18', 'user19', 'user20', 'user21', 'user22', 'user23', 'user24']

Number of users: 18

In [19]:
print("\nTEST DIRECTORIES")

test_trials = sorted(glob.glob(TEST + "/SM_test_*"))

print("Number of test trials:", len(test_trials))

for x in test_trials[:20]:
    print(os.path.basename(x))

TEST DIRECTORIES
Number of test trials: 405
SM_test_0001
SM_test_0002
SM_test_0003
SM_test_0004
SM_test_0005
SM_test_0006
SM_test_0007
SM_test_0008
SM_test_0009
SM_test_0010
SM_test_0011
SM_test_0012
SM_test_0013
SM_test_0014
SM_test_0015
SM_test_0016
SM_test_0017
SM_test_0018
SM_test_0019
SM_test_0020

In [20]:
import os

root = "/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Skeleton"

for action in sorted(os.listdir(root))[:3]:
    action_dir = os.path.join(root, action)

    if not os.path.isdir(action_dir):
        continue

    print("\nACTION:", action)

    for user in sorted(os.listdir(action_dir))[:3]:
        user_dir = os.path.join(action_dir, user)

        if not os.path.isdir(user_dir):
            continue

        trials = sorted(os.listdir(user_dir))

        print(user, ":", trials[:15])

ACTION: 0_Wash_face
user16 : ['1-1-1', '1-1-2', '1-1-3']
user18 : ['7-1-1', '7-1-2', '7-1-3']
user20 : ['4-2-1', '4-2-2', '4-2-3']

ACTION: 10_Stir_drinks
user1 : ['2-1-1', '2-1-2', '2-1-3', '3-1-1', '3-1-2', '3-1-3', '4-1-1']
user16 : ['1-2-1', '1-2-2', '1-2-3', '2-1-1', '2-1-2', '2-1-3', '7-2-1', '7-2-2', '7-2-3']
user17 : ['2-1-1', '2-1-2', '2-1-3', '2-2-1', '2-2-2', '2-2-3', '5-2-1', '5-2-2', '5-2-3']

ACTION: 11_Peel_fruits
user1 : ['1-2-1', '1-2-2', '4-1-1', '4-1-2', '4-1-3', '6-1-1', '6-1-2', '6-1-3']
user16 : ['1-2-1', '1-2-2', '1-2-3', '3-2-1', '3-2-2', '3-2-3', '5-2-1', '5-2-2', '5-2-3']
user17 : ['7-2-1', '7-2-2', '7-2-3']

---

In [21]:
from pathlib import Path
TRAIN_DATA = Path(
    "/kaggle/input/datasets/samasiayushman/small-model-track/"
    "Training/Training/data"
)

TEST_DATA = Path(
    "/kaggle/input/datasets/samasiayushman/small-model-track/"
    "Testing/Testing/small_model_track_test-007/small_model_track_test"
)

CLASS_MAPPING = pd.read_csv(
    TRAIN_DATA.parent / "class_mapping.csv"
)

CLASS_MAPPING.head()

   action_id         action_name
0          0         0_Wash_face
1          1       1_Brush_teeth
2          2         2_Comb_hair
3          3  3_Take_off_clothes
4          4        4_Wipe_hands

In [22]:
from pathlib import Path
import pandas as pd

TRAIN_DATA = Path(
    "/kaggle/input/datasets/samasiayushman/small-model-track/"
    "Training/Training/data"
)

SKELETON_DATA = TRAIN_DATA / "Skeleton"

records = []

for action_dir in sorted(SKELETON_DATA.iterdir()):
    if not action_dir.is_dir():
        continue

    action_name = action_dir.name
    label = int(action_name.split("_", 1)[0])

    for user_dir in sorted(action_dir.iterdir()):
        if not user_dir.is_dir():
            continue

        user = user_dir.name

        for trial_dir in sorted(user_dir.iterdir()):
            if not trial_dir.is_dir():
                continue

            records.append({
                "action": action_name,
                "label": label,
                "user": user,
                "trial": trial_dir.name,
                "path": str(trial_dir),
            })

train_df = pd.DataFrame(records)

print("Training trials:", len(train_df))
print()
print(train_df.head())

Training trials: 2931

        action  label    user  trial  \
0  0_Wash_face      0  user16  1-1-1
1  0_Wash_face      0  user16  1-1-2
2  0_Wash_face      0  user16  1-1-3
3  0_Wash_face      0  user18  7-1-1
4  0_Wash_face      0  user18  7-1-2

                                                path
0  /kaggle/input/datasets/samasiayushman/small-mo...
1  /kaggle/input/datasets/samasiayushman/small-mo...
2  /kaggle/input/datasets/samasiayushman/small-mo...
3  /kaggle/input/datasets/samasiayushman/small-mo...
4  /kaggle/input/datasets/samasiayushman/small-mo...

In [23]:
print(train_df.shape)

print("\nClasses:")
print(train_df["label"].nunique())

print("\nUsers:")
print(train_df["user"].nunique())

print("\nTrials per user:")
print(train_df["user"].value_counts().sort_index())

print("\nTrials per class:")
print(train_df["label"].value_counts().sort_index())

(2931, 5)

Classes:
40

Users:
18

Trials per user:
user
user1     149
user16    186
user17    166
user18    178
user19    186
user2     167
user20    159
user21    133
user22    191
user23    131
user24    159
user3     161
user4     134
user5     100
user6     201
user7     184
user8     165
user9     181
Name: count, dtype: int64

Trials per class:
label
0      44
1      48
2      54
3      41
4      70
5      57
6     120
7     154
8      97
9     131
10    117
11    106
12     63
13     56
14     35
15     52
16     24
17     86
18     38
19     43
20     94
21     73
22     59
23     75
24     48
25     12
26     40
27     41
28     37
29     77
30     44
31     85
32     84
33     33
34    147
35     26
36    335
37     68
38     62
39     55
Name: count, dtype: int64

In [24]:
MODALITIES = {
    "skeleton": TRAIN_DATA / "Skeleton",
    "depth_color": TRAIN_DATA / "Depth_Color",
    "ir": TRAIN_DATA / "IR",
    "thermal": TRAIN_DATA / "Thermal",
    "imu": TRAIN_DATA / "IMU",
    "radar": TRAIN_DATA / "Radar",
}

def get_modality_path(row, modality):
    path = (
        MODALITIES[modality]
        / row["action"]
        / row["user"]
        / row["trial"]
    )
    
    return str(path) if path.exists() else None


for modality in MODALITIES:
    train_df[modality] = train_df.apply(
        lambda row: get_modality_path(row, modality),
        axis=1
    )

train_df.head()

,action,label,user,trial,path,skeleton,depth_color,ir,thermal,imu,radar
0,0_Wash_face,0,user16,1-1-1,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
1,0_Wash_face,0,user16,1-1-2,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
2,0_Wash_face,0,user16,1-1-3,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
3,0_Wash_face,0,user18,7-1-1,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
4,0_Wash_face,0,user18,7-1-2,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...

In [25]:
print("===== MISSING MODALITIES =====")

for modality in MODALITIES:
    missing = train_df[modality].isna().sum()
    print(f"{modality:15s}: {missing}")

===== MISSING MODALITIES =====
skeleton       : 0
depth_color    : 0
ir             : 0
thermal        : 145
imu            : 28
radar          : 17

In [26]:
row = train_df.iloc[0]

print("ACTION :", row["action"])
print("LABEL  :", row["label"])
print("USER   :", row["user"])
print("TRIAL  :", row["trial"])

print("\nMODALITY PATHS")

for modality in MODALITIES:
    print(f"\n{modality}:")
    print(row[modality])

ACTION : 0_Wash_face
LABEL  : 0
USER   : user16
TRIAL  : 1-1-1

MODALITY PATHS

skeleton:
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Skeleton/0_Wash_face/user16/1-1-1

depth_color:
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Depth_Color/0_Wash_face/user16/1-1-1

ir:
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IR/0_Wash_face/user16/1-1-1

thermal:
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Thermal/0_Wash_face/user16/1-1-1

imu:
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/0_Wash_face/user16/1-1-1

radar:
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Radar/0_Wash_face/user16/1-1-1

In [27]:
import os
from pathlib import Path

row = train_df.iloc[0]

print("=" * 70)
print("TRIAL INSPECTION")
print("=" * 70)

print("Action :", row["action"])
print("Label  :", row["label"])
print("User   :", row["user"])
print("Trial  :", row["trial"])

for modality in MODALITIES:

    path = Path(row[modality])

    print("\n" + "=" * 70)
    print(modality.upper())
    print("=" * 70)

    if not path.exists():
        print("MISSING")
        continue

    files = list(path.iterdir())

    print("Path :", path)
    print("Files:", len(files))

    # Show first 5 files
    for f in sorted(files)[:5]:
        print("  ", f.name)

    if len(files) > 5:
        print("   ...")

======================================================================
TRIAL INSPECTION
======================================================================
Action : 0_Wash_face
Label  : 0
User   : user16
Trial  : 1-1-1

======================================================================
SKELETON
======================================================================
Path : /kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Skeleton/0_Wash_face/user16/1-1-1
Files: 1
   predictions

======================================================================
DEPTH_COLOR
======================================================================
Path : /kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Depth_Color/0_Wash_face/user16/1-1-1
Files: 47
   Depth_2025-06-10_10-43-49.016_00000151_Color.png
   Depth_2025-06-10_10-43-49.116_00000152_Color.png
   Depth_2025-06-10_10-43-49.216_00000153_Color.png
   Depth_2025-06-10_10-43-49.316_00000154_Color.png
   Depth_2025-06-10_10-43-49.416_00000155_Color.png
   ...

======================================================================
IR
======================================================================
Path : /kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IR/0_Wash_face/user16/1-1-1
Files: 47
   IR_2025-06-10_10-43-49.016_00000151.png
   IR_2025-06-10_10-43-49.116_00000152.png
   IR_2025-06-10_10-43-49.216_00000153.png
   IR_2025-06-10_10-43-49.316_00000154.png
   IR_2025-06-10_10-43-49.416_00000155.png
   ...

======================================================================
THERMAL
======================================================================
Path : /kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Thermal/0_Wash_face/user16/1-1-1
Files: 106
   frame_000389.jpg
   frame_000390.jpg
   frame_000391.jpg
   frame_000392.jpg
   frame_000393.jpg
   ...

======================================================================
IMU
======================================================================
Path : /kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/IMU/0_Wash_face/user16/1-1-1
Files: 2
   down(LL+RL).csv
   up(LA+RA+C).csv

======================================================================
RADAR
======================================================================
Path : /kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Radar/0_Wash_face/user16/1-1-1
Files: 1
   radar_output_T2025-06-10_10-43-36.157.csv

In [28]:
import json
from pathlib import Path

row = train_df.iloc[0]

skeleton_path = Path(row["skeleton"]) / "predictions"

print("Skeleton predictions path:")
print(skeleton_path)

files = sorted(skeleton_path.glob("*.json"))

print("\nNumber of JSON files:", len(files))

print("\nFirst 5 files:")
for f in files[:5]:
    print(f.name)

# Load first JSON
with open(files[0], "r") as f:
    data = json.load(f)

print("\n" + "=" * 70)
print("FIRST SKELETON JSON")
print("=" * 70)

print("Python type:", type(data))

if isinstance(data, dict):
    print("Keys:", list(data.keys()))

print("\nContent:")
print(data)

Skeleton predictions path:
/kaggle/input/datasets/samasiayushman/small-model-track/Training/Training/data/Skeleton/0_Wash_face/user16/1-1-1/predictions

Number of JSON files: 47

First 5 files:
Color_2025-06-10_10-43-49.016_00000151.json
Color_2025-06-10_10-43-49.116_00000152.json
Color_2025-06-10_10-43-49.216_00000153.json
Color_2025-06-10_10-43-49.316_00000154.json
Color_2025-06-10_10-43-49.416_00000155.json

======================================================================
FIRST SKELETON JSON
======================================================================
Python type: <class 'list'>

Content:
[{'keypoints': [[-0.0, 0.0, 0.41915184259414673], [-0.06608593463897705, 0.0276512261480093, 0.46736639738082886], [0.066192626953125, 0.03570188209414482, 0.1520582139492035], [0.022212767973542213, 0.1488175094127655, 0.03478503227233887], [-0.02752356044948101, -0.09068717807531357, 0.4411424398422241], [0.104872927069664, -0.04890204593539238, 0.11597716808319092], [0.055329956114292145, 0.04949260503053665, 0.0], [0.043074220418930054, -0.025653760880231857, 0.670325517654419], [0.17981885373592377, -0.01677960902452469, 1.0043519735336304], [0.498803049325943, 0.06383749842643738, 0.9736740589141846], [0.557180643081665, 0.016241418197751045, 1.0341726541519165], [0.22478528320789337, -0.10609500110149384, 1.0104258060455322], [0.2470998466014862, -0.18809570372104645, 0.5426101088523865], [0.5147289633750916, -0.0839303582906723, 0.42910465598106384], [0.15222375094890594, 0.12992529571056366, 1.0426074266433716], [0.21741686761379242, 0.03194200620055199, 0.5985302925109863], [0.4624234139919281, 0.11301489174365997, 0.4472831189632416]], 'keypoint_scores': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]}]

In [29]:
import json
import numpy as np
from pathlib import Path


def load_skeleton(trial_path):
    """
    Load all skeleton JSON frames from one trial.

    Returns:
        keypoints:      [T, 17, 3]
        scores:         [T, 17]
    """

    trial_path = Path(trial_path)
    prediction_dir = trial_path / "predictions"

    json_files = sorted(prediction_dir.glob("*.json"))

    keypoints = []
    scores = []

    for json_file in json_files:

        with open(json_file, "r") as f:
            data = json.load(f)

        # No detected person
        if len(data) == 0:
            keypoints.append(np.zeros((17, 3), dtype=np.float32))
            scores.append(np.zeros(17, dtype=np.float32))
            continue

        # First detected person
        person = data[0]

        kp = np.asarray(
            person["keypoints"],
            dtype=np.float32
        )

        score = np.asarray(
            person["keypoint_scores"],
            dtype=np.float32
        )

        keypoints.append(kp)
        scores.append(score)

    if len(keypoints) == 0:
        return (
            np.empty((0, 17, 3), dtype=np.float32),
            np.empty((0, 17), dtype=np.float32)
        )

    keypoints = np.stack(keypoints)
    scores = np.stack(scores)

    return keypoints, scores

In [30]:
row = train_df.iloc[0]

skeleton, scores = load_skeleton(row["skeleton"])

print("Skeleton shape:", skeleton.shape)
print("Scores shape:", scores.shape)

print("\nData type:", skeleton.dtype)

print("\nFirst frame:")
print(skeleton[0])

print("\nFirst frame scores:")
print(scores[0])

print("\nMin:", skeleton.min())
print("Max:", skeleton.max())

Skeleton shape: (47, 17, 3)
Scores shape: (47, 17)

Data type: float32

First frame:
[[-0.          0.          0.41915184]
 [-0.06608593  0.02765123  0.4673664 ]
 [ 0.06619263  0.03570188  0.15205821]
 [ 0.02221277  0.14881751  0.03478503]
 [-0.02752356 -0.09068718  0.44114244]
 [ 0.10487293 -0.04890205  0.11597717]
 [ 0.05532996  0.04949261  0.        ]
 [ 0.04307422 -0.02565376  0.6703255 ]
 [ 0.17981885 -0.01677961  1.004352  ]
 [ 0.49880305  0.0638375   0.97367406]
 [ 0.55718064  0.01624142  1.0341727 ]
 [ 0.22478528 -0.106095    1.0104258 ]
 [ 0.24709985 -0.1880957   0.5426101 ]
 [ 0.51472896 -0.08393036  0.42910466]
 [ 0.15222375  0.1299253   1.0426074 ]
 [ 0.21741687  0.03194201  0.5985303 ]
 [ 0.4624234   0.11301489  0.44728312]]

First frame scores:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Min: -0.1880957
Max: 1.3082819

In [31]:
print("Score min:", scores.min())
print("Score max:", scores.max())
print("Score mean:", scores.mean())

print("\nUnique scores:")
print(np.unique(scores)[:30])

Score min: 1.0
Score max: 1.0
Score mean: 1.0

Unique scores:
[1.]

In [32]:
import json

empty_frames = 0
multi_person_frames = 0
total_frames = 0

for json_file in sorted(
    Path(row["skeleton"]) .joinpath("predictions").glob("*.json")
):

    with open(json_file, "r") as f:
        data = json.load(f)

    total_frames += 1

    if len(data) == 0:
        empty_frames += 1

    elif len(data) > 1:
        multi_person_frames += 1

print("Total frames:", total_frames)
print("Empty frames:", empty_frames)
print("Multi-person frames:", multi_person_frames)

Total frames: 47
Empty frames: 0
Multi-person frames: 0

## Build the canonical trial dataframe

In [33]:
from pathlib import Path
import pandas as pd

TRAIN_DATA = Path(
    "/kaggle/input/datasets/samasiayushman/"
    "small-model-track/Training/Training/data"
)

records = []

SKELETON_ROOT = TRAIN_DATA / "Skeleton"

for action_dir in sorted(SKELETON_ROOT.iterdir()):

    if not action_dir.is_dir():
        continue

    action_name = action_dir.name
    label = int(action_name.split("_", 1)[0])

    for user_dir in sorted(action_dir.iterdir()):

        if not user_dir.is_dir():
            continue

        user = user_dir.name

        for trial_dir in sorted(user_dir.iterdir()):

            if not trial_dir.is_dir():
                continue

            records.append({
                "action": action_name,
                "label": label,
                "user": user,
                "trial": trial_dir.name,
                "path": trial_dir,
            })

train_df = pd.DataFrame(records)

print("Training trials:", len(train_df))
print("Classes:", train_df["label"].nunique())
print("Users:", train_df["user"].nunique())

train_df.head()

Training trials: 2931
Classes: 40
Users: 18

,action,label,user,trial,path
0,0_Wash_face,0,user16,1-1-1,/kaggle/input/datasets/samasiayushman/small-mo...
1,0_Wash_face,0,user16,1-1-2,/kaggle/input/datasets/samasiayushman/small-mo...
2,0_Wash_face,0,user16,1-1-3,/kaggle/input/datasets/samasiayushman/small-mo...
3,0_Wash_face,0,user18,7-1-1,/kaggle/input/datasets/samasiayushman/small-mo...
4,0_Wash_face,0,user18,7-1-2,/kaggle/input/datasets/samasiayushman/small-mo...

In [34]:
MODALITIES = [
    "Skeleton",
    "Depth_Color",
    "IR",
    "Thermal",
    "IMU",
    "Radar",
]

for modality in MODALITIES:

    train_df[modality.lower()] = train_df.apply(
        lambda row: TRAIN_DATA
        / modality
        / row["action"]
        / row["user"]
        / row["trial"],
        axis=1
    )

train_df.head()

,action,label,user,trial,path,skeleton,depth_color,ir,thermal,imu,radar
0,0_Wash_face,0,user16,1-1-1,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
1,0_Wash_face,0,user16,1-1-2,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
2,0_Wash_face,0,user16,1-1-3,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
3,0_Wash_face,0,user18,7-1-1,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...
4,0_Wash_face,0,user18,7-1-2,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...,/kaggle/input/datasets/samasiayushman/small-mo...

In [35]:
for modality in MODALITIES:

    column = modality.lower()

    train_df[f"{column}_exists"] = train_df[column].apply(
        lambda p: p.exists()
    )

for modality in MODALITIES:
    column = modality.lower()

    print(
        f"{modality:12s}: "
        f"missing = {(~train_df[f'{column}_exists']).sum()}"
    )

Skeleton    : missing = 0
Depth_Color : missing = 0
IR          : missing = 0
Thermal     : missing = 145
IMU         : missing = 28
Radar       : missing = 17

In [36]:
import json
import numpy as np


def load_skeleton(trial_path):

    pred_dir = trial_path / "predictions"

    json_files = sorted(pred_dir.glob("*.json"))

    frames = []
    scores = []

    for json_file in json_files:

        with open(json_file, "r") as f:
            data = json.load(f)

        # Empty frame
        if len(data) == 0:
            keypoints = np.zeros((17, 3), dtype=np.float32)
            kp_scores = np.zeros(17, dtype=np.float32)

        else:
            # First / only person
            person = data[0]

            keypoints = np.asarray(
                person["keypoints"],
                dtype=np.float32
            )

            kp_scores = np.asarray(
                person["keypoint_scores"],
                dtype=np.float32
            )

        frames.append(keypoints)
        scores.append(kp_scores)

    skeleton = np.stack(frames)
    scores = np.stack(scores)

    return skeleton, scores

In [37]:
row = train_df.iloc[0]

skeleton, scores = load_skeleton(
    row["skeleton"]
)

print("Skeleton shape:", skeleton.shape)
print("Scores shape:", scores.shape)
print("dtype:", skeleton.dtype)

Skeleton shape: (47, 17, 3)
Scores shape: (47, 17)
dtype: float32

In [38]:
from pathlib import Path
import pandas as pd

TRAIN_DATA = Path(
    "/kaggle/input/datasets/samasiayushman/"
    "small-model-track/Training/Training/data"
)

MODALITIES = [
    "Skeleton",
    "Depth_Color",
    "IR",
    "Thermal",
    "IMU",
    "Radar",
]

# ---------------------------------------------------------
# Build trial index from Skeleton
# ---------------------------------------------------------

records = []

skeleton_root = TRAIN_DATA / "Skeleton"

for action_dir in sorted(skeleton_root.iterdir()):

    if not action_dir.is_dir():
        continue

    action_name = action_dir.name
    label = int(action_name.split("_")[0])

    for user_dir in sorted(action_dir.iterdir()):

        if not user_dir.is_dir():
            continue

        user = user_dir.name

        for trial_dir in sorted(user_dir.iterdir()):

            if not trial_dir.is_dir():
                continue

            records.append({
                "action": action_name,
                "label": label,
                "user": user,
                "trial": trial_dir.name,
                "path": str(trial_dir),
            })


train_df = pd.DataFrame(records)

print("Training trials:", len(train_df))
print("Classes:", train_df["label"].nunique())
print("Users:", train_df["user"].nunique())

train_df.head()

Training trials: 2931
Classes: 40
Users: 18

,action,label,user,trial,path
0,0_Wash_face,0,user16,1-1-1,/kaggle/input/datasets/samasiayushman/small-mo...
1,0_Wash_face,0,user16,1-1-2,/kaggle/input/datasets/samasiayushman/small-mo...
2,0_Wash_face,0,user16,1-1-3,/kaggle/input/datasets/samasiayushman/small-mo...
3,0_Wash_face,0,user18,7-1-1,/kaggle/input/datasets/samasiayushman/small-mo...
4,0_Wash_face,0,user18,7-1-2,/kaggle/input/datasets/samasiayushman/small-mo...

In [39]:
user_class_counts = pd.crosstab(
    train_df["user"],
    train_df["label"]
)

print(user_class_counts.shape)
display(user_class_counts)

(18, 40)

label,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
user,,,,,,,,,,,,,,,,,,,,,
user1,0,0,3,0,1,3,6,11,10,6,...,3,3,9,0,12,3,17,0,3,0
user16,3,3,3,0,3,0,12,12,3,9,...,3,0,6,6,9,3,21,3,3,3
user17,0,3,3,3,6,6,0,15,9,9,...,3,6,3,3,12,0,18,3,0,6
user18,3,6,3,6,6,6,2,3,0,9,...,3,9,5,0,3,3,15,6,3,3
user19,0,3,3,3,6,3,6,3,3,9,...,3,6,3,3,9,0,26,6,5,6
user2,0,0,0,0,4,0,12,15,12,4,...,5,11,7,0,11,0,25,3,6,3
user20,3,3,6,0,3,0,6,9,3,15,...,3,3,3,0,0,3,9,3,6,0
user21,6,3,3,0,6,3,6,3,7,3,...,3,0,6,0,0,0,24,3,9,6
user22,5,5,6,6,5,9,9,11,6,6,...,3,9,4,0,14,0,22,3,6,3
user23,3,3,3,6,3,6,1,3,0,1,...,0,6,6,0,4,5,17,5,6,3
user24,6,6,3,0,3,0,6,3,0,0,...,0,3,6,3,12,0,21,6,6,6
user3,0,0,2,0,0,3,9,12,12,6,...,0,6,6,3,7,0,21,6,6,2
user4,3,0,0,2,3,3,6,11,5,6,...,3,3,9,0,3,0,15,3,0,0
user5,3,0,6,0,0,0,15,12,0,12,...,0,0,0,0,6,3,0,0,0,0
user6,3,3,2,0,3,0,12,11,15,9,...,3,0,3,6,13,3,21,3,3,3
user7,0,3,3,6,6,6,3,14,12,9,...,3,6,3,3,17,0,22,3,0,5
user8,6,6,2,6,6,6,3,3,0,9,...,3,9,2,0,6,3,14,6,0,0
user9,0,1,3,3,6,3,6,3,0,9,...,3,5,3,6,9,0,27,6,0,6

In [40]:
user_totals = train_df["user"].value_counts().sort_index()

print(user_totals)

user
user1     149
user16    186
user17    166
user18    178
user19    186
user2     167
user20    159
user21    133
user22    191
user23    131
user24    159
user3     161
user4     134
user5     100
user6     201
user7     184
user8     165
user9     181
Name: count, dtype: int64